version: "3.9"
services:
  code-execution-service:
    build: ./code-execution-service
    environment:
      - DOCKER_HOST=unix:///run/user/1000/docker.sock  # Use rootless Docker socket
      - "REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}"
      - "REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}"
      - "REACT_APP_FIREBASE_DATABASE_URL=${REACT_APP_FIREBASE_DATABASE_URL}"
      - "REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}"
      - "REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}"
      - "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}"
      - "REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}"
      - "REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}"
      - "COMMIT_SHA=${COMMIT_SHA}"
      - "USER_SERVICE_TYPE=${USER_SERVICE_TYPE}"
      - "USER_SERVICE_PROJECT_ID=${USER_SERVICE_PROJECT_ID}"
      - "USER_SERVICE_PRIVATE_KEY_ID=${USER_SERVICE_PRIVATE_KEY_ID}"
      - "USER_SERVICE_PRIVATE_KEY=${USER_SERVICE_PRIVATE_KEY}"
      - "USER_SERVICE_CLIENT_EMAIL=${USER_SERVICE_CLIENT_EMAIL}"
      - "USER_SERVICE_CLIENT_ID=${USER_SERVICE_CLIENT_ID}"
      - "USER_SERVICE_AUTH_URI=${USER_SERVICE_AUTH_URI}"
      - "USER_SERVICE_TOKEN_URI=${USER_SERVICE_TOKEN_URI}"
      - "USER_SERVICE_AUTH_PROVIDER_X509_CERT_URL=${USER_SERVICE_AUTH_PROVIDER_X509_CERT_URL}"
      - "USER_SERVICE_CLIENT_X509_CERT_URL=${USER_SERVICE_CLIENT_X509_CERT_URL}"
      - "USER_SERVICE_UNIVERSE_DOMAIN=${USER_SERVICE_UNIVERSE_DOMAIN}"
      - "COMMIT_SHA=${COMMIT_SHA}"
      - "REACT_APP_ENV=${NODE_ENV}"
    ports:
      - "5004:5004"
    volumes:
      - ./code-execution-service:/app
      - /app/node_modules
    env_file:
      - .env
    # Unfortunately, privileged mode is still required https://github.com/ddev/ddev-gitlab-ci/issues/1
    privileged: true
networks:
  default:
    external:
      name: cloudbuild